// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::drivebasesubleft1;
std::shared_ptr<frc::SpeedController> RobotMap::drivebasesubleft2;
std::shared_ptr<frc::SpeedController> RobotMap::drivebasesubright1;
std::shared_ptr<frc::SpeedController> RobotMap::drivebasesubright2;
std::shared_ptr<frc::RobotDrive> RobotMap::drivebasesubRobotdrive;
std::shared_ptr<frc::SpeedController> RobotMap::scissorliftsubsystemliftup1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    drivebasesubleft1.reset(new frc::VictorSP(3));
    lw->AddActuator("drivebasesub", "left1", std::static_pointer_cast<frc::VictorSP>(drivebasesubleft1));
    
    drivebasesubleft2.reset(new frc::VictorSP(4));
    lw->AddActuator("drivebasesub", "left2", std::static_pointer_cast<frc::VictorSP>(drivebasesubleft2));
    
    drivebasesubright1.reset(new frc::VictorSP(1));
    lw->AddActuator("drivebasesub", "right1", std::static_pointer_cast<frc::VictorSP>(drivebasesubright1));
    
    drivebasesubright2.reset(new frc::VictorSP(2));
    lw->AddActuator("drivebasesub", "right2", std::static_pointer_cast<frc::VictorSP>(drivebasesubright2));
    
    drivebasesubRobotdrive.reset(new frc::RobotDrive(drivebasesubleft1, drivebasesubleft2,
              drivebasesubright1, drivebasesubright2));
    
    drivebasesubRobotdrive->SetSafetyEnabled(false);
        drivebasesubRobotdrive->SetExpiration(0.1);
        drivebasesubRobotdrive->SetSensitivity(0.5);
        drivebasesubRobotdrive->SetMaxOutput(1.0);
        drivebasesubRobotdrive->SetInvertedMotor(frc::RobotDrive::kFrontLeftMotor, true);
        drivebasesubRobotdrive->SetInvertedMotor(frc::RobotDrive::kRearLeftMotor, true);
    scissorliftsubsystemliftup1.reset(new frc::VictorSP(5));
    lw->AddActuator("scissorliftsubsystem", "liftup1", std::static_pointer_cast<frc::VictorSP>(scissorliftsubsystemliftup1));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
